spring.application.name=spendfy
spring.profiles.active=${APP_PROFILE:prod}

server.port=${PORT:8080}

# Configurações comuns de JPA
spring.jpa.open-in-view=false

# Configuração de CORS
app.cors.origins=${ALLOWED_ORIGINS:http://localhost:5173}